export type { NumericReduction } from "modality-ts/core";
export {
  applyInputClassAbstraction,
  applyInputClassToWideInputVars,
  applyIntervalAbstraction,
  applyPredicateAbstraction,
  applySaturationCounter,
  attachNumericReductions,
  collectModelNumericReductions,
  collectNumericCutPoints,
  collectNumericObservations,
  downgradeVerdictForReductions,
  exactFirstReduction,
  type InputClassConfig,
  type IntervalAbstractionConfig,
  mergeNumericReductions,
  numericCoiDroppedReductions,
  type PredicateAbstractionConfig,
  reductionsAffectingProperty,
  type SaturationCounterConfig,
  worstNumericClaim,
} from "./ts/numeric/abstraction.js";
